let tempEmployees = [
    {
        id: 1,
        name: "username1",
        first_name: "firstname1",
        last_name: "lastname1",
        email: "email1",
        department: "Z",
        pensum: "pensum1",
        project_create: true,
        project_update: true,
        project_delete: false,
        monument_create: true,
        monument_update: true,
        monument_delete: false,
        document_create: true,
        document_update: true,
        document_delete: false,
        milestone_create: true,
        milestone_update: true,
        milestone_delete: false,
        task_create: true,
        task_update: true,
        task_delete: false,
        isAdmin: false,
    },
    {
        id: 2,
        name: "username2",
        first_name: "firstname2",
        last_name: "lastname2",
        email: "email2",
        department: "K",
        pensum: "pensum2",
        project_create: true,
        project_update: true,
        project_delete: true,
        monument_create: false,
        monument_update: false,
        monument_delete: false,
        document_create: false,
        document_update: false,
        document_delete: false,
        milestone_create: false,
        milestone_update: false,
        milestone_delete: false,
        task_create: true,
        task_update: true,
        task_delete: false,
        isAdmin: false,
    },
    {
        id: 3,
        name: "username3",
        first_name: "firstname3",
        last_name: "lastname3",
        email: "email3",
        department: "S",
        pensum: "pensum3",
        project_create: false,
        project_update: true,
        project_delete: false,
        monument_create: false,
        monument_update: true,
        monument_delete: false,
        document_create: false,
        document_update: false,
        document_delete: false,
        milestone_create: true,
        milestone_update: true,
        milestone_delete: false,
        task_create: true,
        task_update: true,
        task_delete: false,
        isAdmin: false,
    }
];

module.exports = {
    tempEmployees
};